module.exports = function() {

    return this
            .title('bench').helpful()
            .arg()
                .name('treeish-list')
                .title('List of treeish to compare')
                .arr()
                .end()
            .opt()
                .name('benchmarks')
                .short('b').long('benchmark')
                .arr()
                .title('List of required benchmark entity')
                .end()
            .opt()
                .name('without-current-state')
                .short('w').long('wcs')
                .arr()
                .title('Run benchmarks without current state, only revision')
                .end()
            .opt()
                .name('only-bench')
                .short('ob').long('only-bench')
                .arr()
                .title('Run benchmarks on latest make')
                .end()
            .opt()
                .name('delta-rme')
                .short('dr').long('delta-rme')
                .arr()
                .title('Delta for RME')
                .end()
            .opt()
                .name('delta-hz')
                .short('dh').long('delta-hz')
                .arr()
                .title('Delta for HZ')
                .end()
            .act(function(opts,args) {
                return require('../bench')(opts, args).start();
            })
        .end();
};

