module.exports = function() {

    return this
            .title('Benchmarks')
            .helpful()
            .arg()
                .name('treeish-list')
                .title('List of revisions to compare (git treeish)')
                .arr()
                .req()
                .end()
            .opt()
                .name('benchmarks')
                .short('b').long('benchmark')
                .arr()
                .title('List of benchmarks to run')
                .end()
            .opt()
                .name('no-wc')
                .short('w').long('no-wc')
                .flag()
                .title('Run benchmarks without using working copy, use only specified revisions')
                .end()
            .opt()
                .name('no-make')
                .short('m').long('no-make')
                .flag()
                .title('Do not make, run benchmarks only')
                .end()
            .opt()
                .name('delta-rme')
                .short('dr').long('delta-rme')
                .title('Delta for RME')
                .end()
            .opt()
                .name('delay')
                .short('d').long('delay')
                .title('Delay between benchmarks')
                .end()
            .act(function(opts,args) {
                return require('../bench')(opts, args).start();
            })
        .end();
};

